
services:
  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    volumes:
      - ./bot:/app/bot
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  admin_panel:
    build:
      context: .
      dockerfile: admin_panel/Dockerfile
    volumes:
      - ./admin_panel:/app/admin_panel
      - ./logs:/app/logs
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data: 